### PR TITLE
update for 1.0.0-MF

### LINKED ISSUE #8: Update to reflect 1.0.0-MF
Remove FunctorFilter, TraverseFilter, MonadCombine, MonadFilter, MonadReader, MonadState, MonadWriter, TransLift.

Mark MonadError as in cats-core.

Replace Split with CommutativeArrow.

Add InjectK, NonEmptyTraverse, CommutativeFlatMap, CommutativeMonad.

### PR DESCRIPTION
**Pull request by tpolecat**
Updates for 1.0.0-MF, adds MTL

resolves #8

### CODE REVIEW

**Comment by tpolecat** [comment]
I'd appreciate a look by @edmundnoble for MTL and @kailuowang for general sanity. The PDF should be viewable.

**Comment by iravid** [comment]
@tpolecat, I applaud your sense of aesthetics - looks awesome! :-)

**Comment by tpolecat** [comment]
@iravid cool, thanks for doing the hard part!

**Comment by tpolecat** [comment]
The `CoflatMap` → `Functor` line bothers me. I'll fix the spacing.

**Comment by kailuowang** [comment]
👍  Looks awesome to me. Thanks so much, @tpolecat and @iravid.

**Pull request merged**
