### PR TITLE
Update inforgraphic to reflect cats 1.0

### LINKED ISSUE #8: Update to reflect 1.0.0-MF
Remove FunctorFilter, TraverseFilter, MonadCombine, MonadFilter, MonadReader, MonadState, MonadWriter, TransLift.

Mark MonadError as in cats-core.

Replace Split with CommutativeArrow.

Add InjectK, NonEmptyTraverse, CommutativeFlatMap, CommutativeMonad.

### PR DESCRIPTION
**Pull request by iravid**
Resolves #8.

The SVG is removed as I don't have OmniGraffle Pro for the export.

### CODE REVIEW

**Comment by tpolecat** [comment]
Thanks! I'll fork this and add the svg and possibly MTL.

**Comment by fommil** [comment]
for SVG, have you tried Inkscape?

**Comment by tpolecat** [comment]
@fommil no, I'll take a look.

**Comment by tpolecat** [comment]
forked as #10

**Pull request closed without merging**
